// Generated by libraries/CMakeLists.txt

#include <MaterialXLibrary/EmbeddedLibrary.h>

#include <string>
#include <unordered_map>

MATERIALX_NAMESPACE_BEGIN

const std::string& readEmbeddedSourceFile(const std::string& filename) {
    static const std::string missingFileContents = "MISSING SOURCE";
    static const std::unordered_map<std::string, std::string> embeddedFiles = {

    {"README.md",R"a(
THE CONTENTS )")a"},
    {"bxdf/disney_principled.mtlx",R"a(
THE CONTENTS )")a"},
    {"bxdf/gltf_pbr.mtlx",R"a(
THE CONTENTS )")a"}
    };

    auto it = embeddedFiles.find(filename);
    if (it == embeddedFiles.end())
        return missingFileContents;
    return it->second;
}

MATERIALX_NAMESPACE_END

